strDirIn	= '/mnt/tsestudies/wertheimer/gridop/data/store/pca-50/';
strDirOut	= '/home/alex/studies/gridop/figures/S2/pca/timecourse';
strSubject	= '04oct13as';

kPCA	= [1 2 3 50];
nPCA	= numel(kPCA);

cROI	= 	{
				'ppc'
				'pcu'
			};
nROI	= numel(cROI);

colMask	=	[
				0	160	0	%ppc
				224	144	0	%pcu
			]/255;

for kR=1:nROI
	strPathPCA	= PathUnsplit(DirAppend(strDirIn,sprintf('%s-%s',strSubject,cROI{kR})),'melodic_white','');
	
	pca		= str2array(fget(strPathPCA));
	
	kROI	= 1:164;	%one run's worth
	
	for kP=1:nPCA
		kCur	= kPCA(kP);
		k		= size(pca,1) - kCur + 1;
		pcaCur	= 2*normalize(pca(k,kROI),'prctile',0.01)-1;
		
		h	= alexplot(pcaCur,...
				'color'			, colMask(kR,:)	, ...
				'ymin'			, -1			, ...
				'ymax'			, 1				, ...
				'linewidth'		, 1.5			, ...
				'axiswidth'		, 1.5			, ...
				'pgrid'			, 2				, ...
				'axistype'		, 'zero'		, ...
				'showyvalues'	, false			, ...
				'lax'			, 0.01			, ...
				'wax'			, 0.99			, ...
				'tax'			, 0				, ...
				'hax'			, 1				, ...
				'l'				, 0				, ...
				'w'				, 1350			, ...
				'h'				, 200			  ...
				);
		
		strPathOut	= PathUnsplit(strDirOut,['pca-' cROI{kR} '-' StringFill(kCur,2)],'png');
		fig2png(h.hF,strPathOut);
	end
end
