%fix the negative values in the raw functional data for 18mar14ap and rerun
%preprocessing

strDirFunctional	= '/home/tselab/studies/mentalrotation/data/functional/18mar14ap/';
cPathFunctional		= arrayfun(@(r) PathUnsplit(strDirFunctional,sprintf('data_%02d',r),'nii.gz'),(1:13)','uni',false);

s	= cellfunprogress(@NIfTI.FixOutliers,cPathFunctional);

bRerun			= [s.nOutlier]>0;
cPathFunctional	= cPathFunctional(bRerun);
cPathStructural	= repmat({'/home/alex/studies/mentalrotation/data/structural/18mar14ap/data_brain.nii.gz'},size(cPathFunctional));

[bSuccess,cPathOut,tr]	= FSLFEATPreprocess(cPathFunctional,cPathStructural,...
								'motion_correct'		, true			, ...
								'slice_time_correct'	, 6				, ...
								'spatial_fwhm'			, 6				, ...
								'norm_intensity'		, false			, ...
								'highpass'				, 100			, ...
								'lowpass'				, false			, ...
								'force'					, true			, ...
								'nthread'				, 12			  ...
								);

cPathPP						= arrayfun(@(r) PathUnsplit(strDirFunctional,sprintf('data_%02d-pp',r),'nii.gz'),(1:13)','uni',false);
[b,cPathCat,cDirFEATCat]	= FSLConcatenate(cPathPP,...
									'nthread'	, 12	, ...
									'force'		, true	  ...
									);
