% Analysis_20150320_ROICCMVPA.m
% ROI cross-classification analysis between each ROI from ROIMVPA
nThread	= 12;

dimPCA	= 50;

%create directory for analysis results
	strNameAnalysis	= '20150320_roiccmvpa';
	strDirOut		= DirAppend(strDirAnalysis, strNameAnalysis);
	CreateDirPath(strDirOut);

%get subject info
	ifo			= MR.SubjectInfo;
	cSession	= ifo.code.fmri;

%get masks
	cMask	= MR.UnionMasks;
	cMask	= cMask.all;

%targets and chunks
	cTarget	= ifo.label.mvpa.target.operation.correct;
	kChunk	= ifo.label.mvpa.chunk.correct;
	
	durRun	= MR.Param('trrun');
	nRun	= size(ifo.operation,2);
	kRun	= reshape(repmat(1:nRun,[durRun 1]),[],1);

%ROI Cross-classification!
	conf	= MR.ConfusionModels;
	conf	= conf{1};
	
	res	= MVPAROICrossClassify(...
			'output_dir'		, strDirOut		, ...
			'dir_data'			, strDirData	, ...
			'subject'			, cSession		, ...
			'mask'				, cMask			, ...
			'mask_variant'		, 'unique'		, ...
			'dim'				, dimPCA		, ...
			'targets'			, cTarget		, ...
			'chunks'			, kChunk		, ...
			'target_blank'		, 'Blank'		, ...
			'zscore'			, kRun			, ...
			'spatiotemporal'	, true			, ...
			'confusion_model'	, conf			, ...
			'debug'				, 'all'			, ...
			'nthread'			, nThread		, ...
			'force'				, false			  ...
			);

%save the results
	strPathOut	= PathUnsplit(strDirOut,'result','mat');
	save(strPathOut,'res');
