% Analysis_20160113_ROIMVPA_ControlROI
% like Analysis_20150318_ROIMVPA but with control ROIs.
% RUN MR.Preprocess.MasksControl FIRST!
% Updated: 2016-01-13
% Copyright 2016 Alex Schlegel (schlegel@gmail.com).  This work is licensed
% under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported
% License.
nCore	= 12;

dimPCAMin	= 10;

%create directory for analysis results
	strNameAnalysis	= '20160113_roimvpa_controlroi';
	strDirOut		= DirAppend(strDirAnalysis, strNameAnalysis);
	CreateDirPath(strDirOut);

%get subject info
	ifo			= MR.SubjectInfo;
	cSession	= ifo.code.fmri;

%get masks
	cMask	=	{
					'mfc'
					'mtl'
					'thal'
					'brainstem'
					'dstriatum'
				};
	

%targets and chunks
	cTarget	= ifo.label.mvpa.target.operation.correct;
	kChunk	= ifo.label.mvpa.chunk.correct;
	
	cTargetSubset	= {'l';'r';'b';'f'};
	
	durRun	= MR.Param('trrun');
	nRun	= size(ifo.operation,2);
	kRun	= reshape(repmat(1:nRun,[durRun 1]),[],1);

%ROI Classification!
	strDirMVPA	= DirAppend(strDirOut,'mvpa');
	
	conf	= MR.ConfusionModels;
	conf	= conf{1};
	
	res	= MVPAROIClassify(...
			'dir_out'			, strDirMVPA	, ...
			'dir_data'			, strDirData	, ...
			'subject'			, cSession		, ...
			'mask'				, cMask			, ...
			'mindim'			, dimPCAMin		, ...
			'targets'			, cTarget		, ...
			'chunks'			, kChunk		, ...
			'target_subset'		, cTargetSubset	, ...
			'target_blank'		, 'Blank'		, ...
			'zscore'			, kRun			, ...
			'spatiotemporal'	, true			, ...
			'confusion_model'	, conf			, ...
			'debug'				, 'all'			, ...
			'debug_multitask'	, 'info'		, ...
			'cores'				, nCore			, ...
			'force'				, false			  ...
			);
	
	%redo the FDR correction (two separate analyses)
		[~,res.result.allway.stats.confusion.corr.pfdr(1:3)] = fdr(res.result.allway.stats.confusion.corr.p(1:3),0.05);
		[~,res.result.allway.stats.confusion.corr.pfdr(4:5)] = fdr(res.result.allway.stats.confusion.corr.p(4:5),0.05);

	%save the results
		strPathOut	= PathUnsplit(strDirOut,'result','mat');    
		save(strPathOut,'res');

%hand classification
	cMaskHand	=	{
						'brainstem'
						'dstriatum'
					};
	
	cTargetSubsetHand	= {'hl';'hr';'hb';'hf'};
	
	strDirMVPAHand	= DirAppend(strDirOut,'mvpahand');
	
	res	= MVPAROIClassify(...
			'dir_out'			, strDirMVPAHand	, ...
			'dir_data'			, strDirData		, ...
			'subject'			, cSession			, ...
			'mask'				, cMaskHand			, ...
			'mindim'			, dimPCAMin			, ...
			'targets'			, cTarget			, ...
			'chunks'			, kChunk			, ...
			'target_subset'		, cTargetSubsetHand	, ...
			'target_blank'		, 'Blank'			, ...
			'zscore'			, kRun				, ...
			'spatiotemporal'	, true				, ...
			'confusion_model'	, conf				, ...
			'debug'				, 'all'				, ...
			'debug_multitask'	, 'info'			, ...
			'cores'				, nCore				, ...
			'force'				, false				  ...
			);
	
	%save the results
		strPathOut	= PathUnsplit(strDirOut,'resulthand','mat');    
		save(strPathOut,'res');
	